name: SAT Alertas

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SAT_RFC: ${{ secrets.SAT_RFC }}
          SAT_CURP: ${{ secrets.SAT_CURP }}
          SAT_EMAIL: ${{ secrets.SAT_EMAIL }}
        run: python bot.py
